name: rook_sdk_health_connect
description: This package enables apps to extract and upload data from Health Connect.
version: 2.4.0
homepage: 'https://docs.tryrook.io/'
platforms:
  android:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ">=2.0.0 <3.0.0"
  protobuf: ">=3.0.0 <4.0.0"
  fixnum: "^1.0.0"
  rook_sdk_core: "^0.4.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rookmotion.rook_sdk_health_connect
        pluginClass: RookSdkHealthConnectPlugin
