name: rook_sdk_core
description: Core functionality for rook_sdk_health_connect and rook_sdk_apple_health packages.
version: 0.4.0
homepage: 'https://docs.tryrook.io/'
platforms:
  android:
  ios:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
# Add dependencies here

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
